/* Dieses SQL wird nur für Test ausgeführt.  */

INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99,  223.45, 'owner1') ;
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 123.45, 'owner1') ;
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 323.45, 'owner2') ;